#!/usr/bin/env python3
"""
Automated GitHub Issue Creation
Reads investigation report and creates GitHub issues automatically
"""

import json
import os
import sys
import subprocess
from typing import List, Dict, Any


class GitHubIssueCreator:
    """Creates GitHub issues from investigation report"""

    def __init__(self, report_path: str, owner: str, repo: str):
        self.report_path = report_path
        self.owner = owner
        self.repo = repo
        self.created_issues = []

    def load_report(self) -> Dict[str, Any]:
        """Load investigation report"""
        with open(self.report_path, 'r') as f:
            return json.load(f)

    def create_issue_body(self, issue: Dict[str, Any]) -> str:
        """Generate issue body in markdown"""

        labels = self._get_labels(issue)

        body = f"""## 🐛 Issue Description

{issue['description']}

---

## 📍 Location

**File:** `{issue['file_path']}`
"""

        if issue.get('line_number', 0) > 0:
            body += f"**Line:** {issue['line_number']}\n"

        body += f"""
---

## 🔄 Reproduction Steps

"""
        for step in issue['reproduction_steps']:
            body += f"{step}\n"

        body += f"""
---

## ✅ Expected Behavior

{issue['expected_behavior']}

---

## ❌ Actual Behavior

{issue['actual_behavior']}

---

## 💥 Impact

{issue['impact']}

---

## 💡 Suggested Fix

{issue['suggested_fix']}

---

## 🏷️ Metadata

- **Severity:** {issue['severity'].upper()}
- **Component:** {issue['component']}
- **Auto-generated:** Yes (Autonomous Investigation System)

---

*This issue was automatically generated by the Autonomous Repository Investigation System.*
"""

        return body

    def _get_labels(self, issue: Dict[str, Any]) -> List[str]:
        """Generate labels for issue"""
        labels = [
            f"severity:{issue['severity']}",
            f"component:{issue['component']}"
        ]

        # Add type label
        if 'security' in issue['title'].lower() or issue['component'] == 'security':
            labels.append('security')
        elif 'test' in issue['title'].lower():
            labels.append('testing')
        elif 'backend' in issue['title'].lower() or issue['component'] == 'backend':
            labels.append('backend')
        elif 'frontend' in issue['title'].lower() or issue['component'] == 'frontend':
            labels.append('frontend')
        elif 'performance' in issue['title'].lower() or issue['component'] == 'performance':
            labels.append('performance')

        # Add bug label for critical/high
        if issue['severity'] in ['critical', 'high']:
            labels.append('bug')
        else:
            labels.append('enhancement')

        return labels

    def create_issues(self, dry_run: bool = False):
        """Create GitHub issues from report"""

        print("📝 Loading investigation report...")
        report = self.load_report()

        print(f"\n📊 Found {report['summary']['total_issues']} issues to create")

        if dry_run:
            print("\n🏃 DRY RUN MODE - No issues will be created\n")

        # Create issues by severity (critical first)
        for severity in ['critical', 'high', 'medium', 'low']:
            issues = report['issues_by_severity'][severity]

            if not issues:
                continue

            print(f"\n{'='*60}")
            print(f"Creating {severity.upper()} severity issues ({len(issues)} total)")
            print(f"{'='*60}\n")

            for idx, issue in enumerate(issues, 1):
                title = f"[{severity.upper()}] {issue['title']}"
                body = self.create_issue_body(issue)
                labels = self._get_labels(issue)

                print(f"{idx}. {title}")

                if dry_run:
                    print(f"   Labels: {', '.join(labels)}")
                    print(f"   File: {issue['file_path']}")
                    continue

                # Create issue using gh CLI
                try:
                    labels_str = ','.join(labels)
                    cmd = [
                        'gh', 'issue', 'create',
                        '--title', title,
                        '--body', body,
                        '--label', labels_str,
                        '--repo', f"{self.owner}/{self.repo}"
                    ]

                    result = subprocess.run(
                        cmd,
                        capture_output=True,
                        text=True,
                        check=True
                    )

                    issue_url = result.stdout.strip()
                    self.created_issues.append({
                        'title': title,
                        'url': issue_url,
                        'severity': severity
                    })

                    print(f"   ✅ Created: {issue_url}")

                except subprocess.CalledProcessError as e:
                    print(f"   ❌ Error: {e.stderr}")
                except Exception as e:
                    print(f"   ❌ Error: {str(e)}")

        # Print summary
        print("\n" + "="*60)
        print("📊 SUMMARY")
        print("="*60)

        if dry_run:
            print(f"\n🏃 DRY RUN - Would create {report['summary']['total_issues']} issues")
        else:
            print(f"\n✅ Created {len(self.created_issues)} issues successfully")

            if self.created_issues:
                print("\n📋 Created Issues:")
                for issue in self.created_issues:
                    print(f"\n  [{issue['severity'].upper()}] {issue['title']}")
                    print(f"  → {issue['url']}")

    def save_created_issues_log(self, output_path: str):
        """Save log of created issues"""
        with open(output_path, 'w') as f:
            json.dump(self.created_issues, f, indent=2)

        print(f"\n📄 Created issues log saved to: {output_path}")


def main():
    """Main entry point"""

    print("""
╔═══════════════════════════════════════════════════════════════╗
║   Automated GitHub Issue Creator                             ║
║   Creates issues from investigation report                   ║
╚═══════════════════════════════════════════════════════════════╝
    """)

    # Get configuration
    report_path = os.getenv('REPORT_PATH', 'investigation_report.json')
    owner = os.getenv('GITHUB_OWNER', 'crespo21')
    repo = os.getenv('GITHUB_REPO', 'Delightful-Group')
    dry_run = os.getenv('DRY_RUN', 'false').lower() == 'true'

    # Check if report exists
    if not os.path.exists(report_path):
        print(f"❌ Error: Report file not found: {report_path}")
        print("   Run autonomous_investigator.py first to generate the report.")
        return 1

    # Check if gh CLI is available
    try:
        subprocess.run(['gh', '--version'], capture_output=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("❌ Error: GitHub CLI (gh) not found.")
        print("   Install it from: https://cli.github.com/")
        return 1

    # Create issues
    creator = GitHubIssueCreator(report_path, owner, repo)
    creator.create_issues(dry_run=dry_run)

    if not dry_run and creator.created_issues:
        log_path = 'created_issues.json'
        creator.save_created_issues_log(log_path)

    print("\n✅ Done!\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
